name: Build and Deploy

on:
  push:
    branches: [master]

#defaults:

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
        working-directory: ./
      - run: npm run build-action
        # continue-on-error: true
        env:
          #          VUE_APP_I18N_LOCALE: ${{ secrets.VUE_APP_I18N_LOCALE }}
          GRAPHQL_URI: ${{ secrets.VUE_APP_API_ENDPOINT }}
      #          VUE_APP_API_ENDPOINT: ${{ secrets.VUE_APP_API_ENDPOINT }}
      #          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      #          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: ls dist
      - run: pwd
      # - run: git status -uno --porcelain
      # - run: git checkout package-lock.json
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/virtual/kritten/projects/gamesdb/frontend/ && rm -rf dist_tmp/ && mkdir dist_tmp
          host: reinmuth.uberspace.de
          username: ${{ secrets.UBERSPACE_NAME }}
          password: ${{ secrets.UBERSPACE_PASSWORD }}
      # - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: sftp://reinmuth.uberspace.de:22/var/www/virtual/kritten/projects/gamesdb/frontend/dist_tmp
      #     ftp-username: ${{ secrets.UBERSPACE_NAME }}
      #     ftp-password: ${{ secrets.UBERSPACE_PASSWORD }}
      #     #          known-hosts: ${{ secrets.UBERSPACE_HOST }}
      #     git-ftp-args: --insecure
      #     local-dir: frontend/dist/pwa
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # ARGS: "-rlgoDzvc -i"
          SOURCE: "frontend/dist/pwa"
          REMOTE_HOST: reinmuth.uberspace.de
          REMOTE_USER: ${{ secrets.UBERSPACE_NAME }}
          TARGET: /var/www/virtual/kritten/projects/gamesdb/frontend/dist_tmp
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
        working-directory: ./
      - run: ls
        working-directory: ./
      - run: ls
      - run: npm run build
        continue-on-error: true
        env:
          #          VUE_APP_I18N_LOCALE: ${{ secrets.VUE_APP_I18N_LOCALE }}
          VUE_APP_API_ENDPOINT: ${{ secrets.VUE_APP_API_ENDPOINT }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          SECRET: ${{ secrets.SECRET }}
      #          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      #          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: ls dist
      - run: pwd
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # ARGS: "-rlgoDzvc -i"
          SOURCE: "backend/dist"
          REMOTE_HOST: reinmuth.uberspace.de
          REMOTE_USER: ${{ secrets.UBERSPACE_NAME }}
          TARGET: /var/www/virtual/kritten/projects/gamesdb/backend/dist_tmp
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
      # - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: sftp://reinmuth.uberspace.de:22/var/www/virtual/kritten/projects/gamesdb/backend/dist_tmp
      #     ftp-username: ${{ secrets.UBERSPACE_NAME }}
      #     ftp-password: ${{ secrets.UBERSPACE_PASSWORD }}
      #     #          known-hosts: ${{ secrets.UBERSPACE_HOST }}
      #     git-ftp-args: --insecure
      #     local-dir: backend/dist
  restart:
    name: Restarts app
    runs-on: ubuntu-latest
    needs:
      - build-frontend
      - build-backend
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/virtual/kritten/projects/gamesdb/ && ./restart.sh
          host: reinmuth.uberspace.de
          username: ${{ secrets.UBERSPACE_NAME }}
          password: ${{ secrets.UBERSPACE_PASSWORD }}
