name: Build and Deploy

on:
  push:
    branches: [master]

#defaults:

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: ls dist
      - run: npm run build-action
        continue-on-error: true
#        env:
#          VUE_APP_I18N_LOCALE: ${{ secrets.VUE_APP_I18N_LOCALE }}
#          VUE_APP_API_ENDPOINT: ${{ secrets.VUE_APP_API_ENDPOINT }}
#          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
#          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: ls
      - run: pwd
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://reinmuth.uberspace.de:22/var/www/virtual/kritten/projects/gamesdb/frontend/dist_tmp
          ftp-username: ${{ secrets.UBERSPACE_NAME }}
          ftp-password: ${{ secrets.UBERSPACE_PASSWORD }}
          #          known-hosts: ${{ secrets.UBERSPACE_HOST }}
          git-ftp-args: --insecure
          local-dir: frontend/dist
  restart:
    name: Restarts app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/virtual/kritten/projects/gamesdb/ && ./restart.sh
          host: reinmuth.uberspace.de
          username: ${{ secrets.UBERSPACE_NAME }}
          password: ${{ secrets.UBERSPACE_PASSWORD }}